velocity:
  # server name
  server: 'lobby'
  # server count
  server-count: 2
  # request time out (ticks)
  request-time-out: 100

message-channel:
  # select PLUGIN_MESSAGE or REDIS
  type: PLUGIN_MESSAGE
  # if you want to use redis, you can set the following properties
  redis:
    host: '127.0.0.1'
    port: 6379
    password: '1234'